### PR TITLE
Move willBeEvaluatedAsCallByCodeGen to OpenJ9

### PR DESCRIPTION
**Pull request by IBMJimmyk**
The `willBeEvaluatedAsCallByCodeGen` implementation for x is almost entirely guarded by the `J9_PROJECT_SPECIFIC` macro. If the macro is not set, it always returns true which is what the default implementation already does. Since this implementation is only meaningful to OpenJ9, it is being moved there.

`willNotInlineCompareAndSwapNative` is only called from this implementation of `willBeEvaluatedAsCallByCodeGen` so it is being moved as well.

Depends on:
https://github.com/eclipse-openj9/openj9/pull/20469
The OpenJ9 PR needs to be merged in either before or at the same time as this one.

### CODE REVIEW

**Comment by IBMJimmyk** [comment]
@hzongaro When you have some time, could you look at this?

**Review by hzongaro — APPROVED** [review]
I think these changes look good.  Thanks!

**Comment by hzongaro** [comment]
Jenkins build all

**Comment by hzongaro** [comment]
Testing was successful.  Downstream change that needed to be merged first &mdash; eclipse-openj9/openj9#20469 &mdash; to prevent downstream breakage has been merged, so this change can be merged.

**Pull request merged**
