### PR TITLE
Simplify base of the FrontEnd hierarchy

### PR DESCRIPTION
**Pull request by 0xdaryl**
Simplify and cleanup the base of the FrontEnd hierarchy in preparation for future refactoring work to provide a consistent base for all downstream projects.

Eliminate FEBase, FECommon, and ConcreteFE as they were part of an early FrontEnd design prior to open sourcing.

Make JitConfig an extensible class in preparation for consuming project specialization.

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins build all

**Comment by AdamBrousseau** [comment]
jenkins build arm,aarch64

**Comment by AdamBrousseau** [comment]
jenkins build arm,aarch64

**Comment by 0xdaryl** [comment]
jenkins build arm,aarch64

**Comment by 0xdaryl** [comment]
jenkins build arm,aarch64

**Comment by 0xdaryl** [comment]
Jenkins build all

**Review by mstoodle — COMMENTED** [review]
Looks pretty good! Thanks for taking this one on, @0xdaryl !

One question I had was why we need both "singleton()" and "instance()" to be public on OMR::FrontEnd . Wouldn't it be better to unify on one of them? Or were you trying to minimize impact of this particular PR?

**Comment by 0xdaryl** [comment]
> Wouldn't it be better to unify on one of them? Or were you trying to minimize impact of this particular PR?

Thanks for the review.  I'll fix this in this PR.

**Review by mstoodle — APPROVED** [review]
lgtm!

**Pull request merged**
