### PR TITLE
Don't zero Offheap after commit

### PR DESCRIPTION
**Pull request by amicic**
Commit on all existing platforms will implicitly (and likely lazily) zero the address range, since we are currently creating Offheap with anonymous small pages.

Hence we are removing our explicit zero call (which was already the case of xLinux).

### CODE REVIEW

**Comment by amicic** [comment]
@dmitripivkine please review

**Review by dmitripivkine — APPROVED** [review]

**Comment by amicic** [comment]
@babsingh, please review/merge

**Comment by amicic** [comment]
and set GC label (can't still do it, probably since rename to eclipse-omr )

**Comment by babsingh** [comment]
jenkins build all

**Review by babsingh — APPROVED** [review]

**Pull request merged**
