### PR TITLE
Extend vmState to pre/post collect

### PR DESCRIPTION
**Pull request by dmitripivkine**
Current vmState for Collector does not include pre- and post- collect. If crash occur in pre- or post- collect vmState can be misleading.

### CODE REVIEW

**Comment by dmitripivkine** [comment]
@amicic Would you please review?

**Review by amicic — APPROVED** [review]

**Comment by amicic** [comment]
jenkins test sanity win jdk11

**Comment by amicic** [comment]
@babsingh please, review, merge

**Comment by babsingh** [comment]
jenkins build all

**Review by babsingh — APPROVED** [review]

**Pull request merged**
