### PR TITLE
Revert "x86: Add disableAVX2/512 options and check XCR0 for OS support"

### PR DESCRIPTION
**Pull request by 0xdaryl**
Reverts eclipse-omr/omr#7510

Causes a Windows build break building x/env/OMRCPU.cpp.

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
Jenkins build all

**Comment by vijaysun-omr** [comment]
Jenkins build riscv

**Comment by dsouzai** [comment]
riscv is a known failure; the infra isn't set up for it.

**Comment by dsouzai** [comment]
also win and zos have no nodes available, so they're also going to fail.

**Comment by vijaysun-omr** [comment]
Thanks @dsouzai I am a bit puzzled by how non-windows builds succeeded either with the original commit. But I will revert now

**Review by vijaysun-omr — APPROVED** [review]

**Comment by keithc-ca** [comment]
Could someone please delete the (now-merged) branch `revert-7510-xcro_flags`? Thanks.

**Pull request merged**
