### PR TITLE
Add cumulative counters to class unloading stats

### PR DESCRIPTION
**Pull request by dmitripivkine**
Add cumulative counters for anonymous classes, classes and classloaders. Add update counters and get cumulative counters API.

### CODE REVIEW

**Comment by dmitripivkine** [comment]
@amicic Would you please review?

**Review by amicic — APPROVED** [review]

**Comment by amicic** [comment]
@babsingh please, proceed with review&merge

**Comment by babsingh** [comment]
jenkins build all

**Comment by babsingh** [comment]
fyi @AdamBrousseau, there is an issue with the infra scripts. otherwise, the changes LGTM.

**Review by babsingh — APPROVED** [review]

**Pull request merged**
