### PR TITLE
Move setmemoryEvaluator() from OMR to Openj9

### PR DESCRIPTION
**Pull request by midronij**
~Use `OMR_GC_SPARSE_HEAP_ALLOCATION` instead of `J9VM_GC_ENABLE_SPARSE_HEAP_ALLOCATION` in `setmemoryEvaluator()`.~

The current implementation of `OMR::Power::setmemoryEvaluator()` has some OpenJ9 dependencies (namely when getting the `classDepthAndFlags` from the object's `J9Class` to generate the [runtime array check](https://github.com/eclipse-omr/omr/blob/5be76769e35bd6bd3dfec8c5237fb87d8a5e81b0/compiler/p/codegen/OMRTreeEvaluator.cpp#L6130-L6149)), and is only ever used by OpenJ9 to generate assembly code for `Unsafe.setMemory()`. Thus, to avoid having to re-implement `setmemoryEvaluator()` to eliminate these OpenJ9 dependencies, we will move it over to OpenJ9 instead.

Depends on https://github.com/eclipse-openj9/openj9/pull/20578

### CODE REVIEW

**Comment by midronij** [comment]
@amicic @0xdaryl @rmnattas I've separated the offheap macro fix into this PR. The change is very simple so hopefully we can merge it soon

**Review by amicic — APPROVED** [review]

**Review by rmnattas — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Jenkins build plinux,aix

**Comment by 0xdaryl** [comment]
Jenkins build plinux,aix

**Comment by midronij** [comment]
I believe the CI failures are happening because my change is dependent on this PR: https://github.com/eclipse-openj9/openj9/pull/20461. I've updated the title/description accordingly

**Comment by amicic** [comment]
> I believe the CI failures are happening because my change is dependent on this PR: [eclipse-openj9/openj9#20461](https://github.com/eclipse-openj9/openj9/pull/20461). I've updated the title/description accordingly

There should not ever be dependancy from OMR code on J9. You might be missing some 'empty' methods in OMR that J9 fully implement.

**Comment by amicic** [comment]
for the failures of missing compressObjectReferences,  follow an example of  contiguousArrayHeaderSizeInBytes()

**Comment by midronij** [comment]
@0xdaryl I rebased my branch and I'm now able to build sucessfully. When you have a moment can you please run the CI tests again?

**Comment by 0xdaryl** [comment]
Jenkins build plinux,aix

**Comment by 0xdaryl** [comment]
There are still failures in the CI builds.  When you said that your build was successful, was that an OpenJ9 build?

The compilers these CI builds are building and testing are either "compilertest" builds or "jitbuilder" builds.  These are not connected to OpenJ9 at all.

To reproduce this locally, if you look at your failed AIX job you can see the "cmake" command that was used to prepare the build (near the beginning of the console output).  Further CMake info is here -> https://github.com/eclipse-omr/omr/blob/master/doc/BuildingWithCMake.md

**Comment by midronij** [comment]
As it turns out, `OMR::Power::setmemoryEvaluator()` (which is where these OpenJ9 dependencies that are causing the CI build to fail are coming from) is only ever used for `Unsafe.setmemory()` in OpenJ9, and is not called anywhere else or in any other downstream projects. However, eliminating these dependencies entirely would be difficult, since in order to perform the [runtime array check](https://github.com/eclipse-omr/omr/blob/5be76769e35bd6bd3dfec8c5237fb87d8a5e81b0/compiler/p/codegen/OMRTreeEvaluator.cpp#L6130-L6149) when offheap is enabled, we need to get the `classDepthAndFlags` from the object's `J9Class`.

After discussin the situation with @0xdaryl, we decided that the best solution may be to simply move `setmemoryEvaluator()` from OMR over to OpenJ9. That being the case, this contribution has been modified to reflect that change, and a matching OpenJ9 PR has been opened here: https://github.com/eclipse-openj9/openj9/pull/20578

**Comment by 0xdaryl** [comment]
Jenkins build plinux,aix

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
