### PR TITLE
Percent and ratio cleanup in trace points

### PR DESCRIPTION
**Pull request by amicic**
For resize group of tracepoints in SchedulingDelegate (Balanced GC in OpenJ9), there is a mixup in prints for ratios and factors (values between 0 and 1) and percents (values between 0 and 100).

To avoid confusion '%' is added after the percent value or explicitly stated it's a ratio (or factor), accordingly.

### CODE REVIEW

**Comment by amicic** [comment]
@dmitripivkine please, review

**Review by dmitripivkine — APPROVED** [review]
Looks correct to me.

**Review by LinHu2016 — APPROVED** [review]
LGTM

**Comment by babsingh** [comment]
jenkins build all

**Review by babsingh — APPROVED** [review]

**Pull request merged**
