### PR TITLE
Fix OpenXL Warnings

### PR DESCRIPTION
**Pull request by matthewhall2**
Suppresses warnings when building on OpenXL

Warnings:
- uninitialized variables
- enum values not handled in switch
- Assignment inside if statement condition
https://hyc-runtimes-jenkins.swg-devops.com/job/jvm.29.personal/34234/

### CODE REVIEW

**Comment by matthewhall2** [comment]
@r30shah please review

**Review by r30shah — CHANGES_REQUESTED** [review]
LGTM. @matthewhall2  can you add more context to commits in this PR ?

**Comment by matthewhall2** [comment]
> LGTM. @matthewhall2 can you add more context to commits in this PR ?

done

**Review by r30shah — APPROVED** [review]
LGTM

**Comment by r30shah** [comment]
jenkins builld all

**Comment by r30shah** [comment]
@hzongaro  Can I request you to review and merge this PR ?

**Comment by r30shah** [comment]
jenkins builld all

**Comment by r30shah** [comment]
Jenkins build all

**Review by hzongaro — COMMENTED** [review]
I think the changes look correct.

May I ask you adjust the summary line of the first commit from "Intialized uninitialized variables" to "Intialize uninitialized variables"?  The [commit guidelines](https://github.com/eclipse-omr/omr/blob/master/CONTRIBUTING.md#commit-guidelines) require the first line to be written in imperative mood.

**Review by hzongaro — APPROVED** [review]
Looks good.  Thanks!

**Comment by hzongaro** [comment]
Jenkins build all

**Comment by AdamBrousseau** [comment]
Jenkins build all

**Comment by hzongaro** [comment]
Looks like the builds are happening, but they're not reflected here.

**Comment by AdamBrousseau** [comment]
jenkins build aarch64

**Comment by AdamBrousseau** [comment]
Jenkins build all

**Comment by hzongaro** [comment]
[Windows failure](https://ci.eclipse.org/omr/job/PullRequest-win_x86-64/4122/) appears to be an infrastructure problem.  Rerunning.

Jenkins build win

**Pull request merged**
