### PR TITLE
Revert "Stop recognizing UTF16_Encoder.encodeUTF16 methods" (2)

### PR DESCRIPTION
**Pull request by knn-k**
This commit restores the changes for encodeUTF16Big and encodeUTF16Little that were removed by #7548.

### CODE REVIEW

**Comment by knn-k** [comment]
This commit depends on #7577 and https://github.com/eclipse-openj9/openj9/pull/20722.

**Comment by knn-k** [comment]
Jenkins build all

**Comment by knn-k** [comment]
I changed the enum symbols `sun_nio_cs_UTF_16_Encoder_encodeUTF16Big` and `sun_nio_cs_UTF_16_Encoder_encodeUTF16Little` to `sun_nio_cs_UTF16_Encoder_encodeUTF16Big` and `sun_nio_cs_UTF16_Encoder_encodeUTF16Little` by removing the `_` between `UTF` and `16` in https://github.com/eclipse-openj9/openj9/pull/20722.

**Review by hzongaro — APPROVED** [review]
Looks good.  Thanks!

**Comment by hzongaro** [comment]
@knn-k, I think this change looks good.  I will wait for you to mark it as "Ready for review" before merging.

**Pull request merged**
