### PR TITLE
Stop recognizing UTF16_Encoder.encodeUTF16 methods

### PR DESCRIPTION
**Pull request by knn-k**
This commit removes the code for encodeUTF16Big() and encodeUTF16Little() methods in sun.nio.cs.UTF16_Encoder from method recognition, and removes related helper functions.

### CODE REVIEW

**Comment by knn-k** [comment]
Jenkins build all

**Comment by knn-k** [comment]
This PR requires a coordinated merge with https://github.com/eclipse-openj9/openj9/pull/20613.

**Review by hzongaro — COMMENTED** [review]
I believe that the only uses of `OMR::CodeGenerator::getSupportsEncodeUtf16LittleWithSurrogateTest`, `OMR::CodeGenerator::getSupportsEncodeUtf16BigWithSurrogateTest` and the JIT option `TR_DisableUTF16BEEncoder` are being removed by OpenJ9 pull request eclipse-openj9/openj9#20613.  I think those methods and option can be removed from OMR.

May I also ask you to correct the name of the class in the commit message?  I believe it was named `sun.nio.cs.UTF16_Encoder`

**Comment by knn-k** [comment]
Jenkins build all

**Comment by knn-k** [comment]
I removed the methods `getSupportsEncodeUtf16LittleWithSurrogateTest()` and `getSupportsEncodeUtf16BigWithSurrogateTest()`, and the JIT option `TR_DisableUTF16BEEncoder` as suggested.
I also corrected the class name in the commit title and the commit message.

**Comment by knn-k** [comment]
Jenkins build all

**Review by hzongaro — APPROVED** [review]
Looks good.  Thanks!

**Pull request merged**
